[build]
  functions = "packages/functions/build"
  publish = "packages/app/build"
  command = "REACT_APP_ENVIRONMENT=netlify yarn"
[build.environment]
  NODE_VERSION = "8.11.2"
  YARN_VERSION = "1.9.4"